//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controladoria.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formulario
    {
        public int idFormulario { get; set; }
        public string Empresa { get; set; }
        public string CNPJ { get; set; }
        public string Matriz { get; set; }
        public string NumNF { get; set; }
        public string NumPedido { get; set; }
        public string NumAP { get; set; }
        public Nullable<System.DateTime> dtVencimento { get; set; }
        public string valorNF { get; set; }
        public Nullable<System.DateTime> dtEmissaoDOC { get; set; }
        public string codJustificativa { get; set; }
        public string Departamento { get; set; }
        public string tipoDocumento { get; set; }
        public string documento { get; set; }
        public Nullable<bool> statusControladoria { get; set; }
        public Nullable<bool> statusFinanceira { get; set; }
        public Nullable<bool> statusComex { get; set; }
        public Nullable<bool> statusPCeAdiantamentos { get; set; }
        public Nullable<bool> statusFiscal { get; set; }
        public Nullable<bool> statusFornecedor { get; set; }
        public Nullable<bool> statusInput { get; set; }
        public Nullable<System.DateTime> dataCadastro { get; set; }
        public string Justificativa { get; set; }
        public Nullable<bool> concluido { get; set; }
        public string loginSolicitante { get; set; }
        public string emailSolicitante { get; set; }
        public string vinculo { get; set; }
        public string tipoContrato { get; set; }
        public Nullable<System.DateTime> contratoInicio { get; set; }
        public Nullable<System.DateTime> contratoFim { get; set; }
        public Nullable<System.DateTime> receitaFederal { get; set; }
        public Nullable<System.DateTime> prefeitura { get; set; }
        public Nullable<System.DateTime> cnae { get; set; }
        public Nullable<bool> optanteSimples { get; set; }
        public Nullable<System.DateTime> optanteSimplesData { get; set; }
        public Nullable<System.DateTime> sintegra { get; set; }
        public Nullable<System.DateTime> juntaComercial { get; set; }
        public Nullable<decimal> IRpct { get; set; }
        public string IRvalor { get; set; }
        public Nullable<decimal> PCCpct { get; set; }
        public string PCCvalor { get; set; }
        public Nullable<decimal> ISSpct { get; set; }
        public string ISSvalor { get; set; }
        public Nullable<decimal> INSSpct { get; set; }
        public string INSSvalor { get; set; }
        public string liquido { get; set; }
        public Nullable<System.DateTime> cadastroMunicipal { get; set; }
        public string CodRetencaoISS { get; set; }
        public string PCCnfs { get; set; }
        public string CFOP { get; set; }
        public Nullable<bool> ZA { get; set; }
        public Nullable<bool> ZS { get; set; }
        public Nullable<bool> NT { get; set; }
        public string codServico { get; set; }
        public string valorDeducao { get; set; }
        public string aliquota { get; set; }
        public string tipoDeDocumento { get; set; }
        public string tributacaoServico { get; set; }
        public string codigoPrestador { get; set; }
        public string atribuicaoISS { get; set; }
        public string situacaoNTFS { get; set; }
        public string ISSretido { get; set; }
        public string registroTributacao { get; set; }
        public string optSimples { get; set; }
        public string tipoNFConv { get; set; }
        public string codServicoMun { get; set; }
        public string tpTribServico { get; set; }
        public string lote { get; set; }
        public Nullable<bool> Reprovado { get; set; }
        public Nullable<bool> Excluido { get; set; }
        public string IRbase { get; set; }
        public string PCCbase { get; set; }
        public string ISSbase { get; set; }
        public string INSSbase { get; set; }
        public string emailResponsavel { get; set; }
    }
}
