//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controladoria.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int idUsuario { get; set; }
        public string Login { get; set; }
        public Nullable<bool> Formulario { get; set; }
        public Nullable<bool> Pesquisar { get; set; }
        public Nullable<bool> Controladoria { get; set; }
        public Nullable<bool> Financeira { get; set; }
        public Nullable<bool> Comex { get; set; }
        public Nullable<bool> PCeAdiantamentos { get; set; }
        public Nullable<bool> Fiscal { get; set; }
        public Nullable<bool> Fornecedor { get; set; }
        public Nullable<bool> Input { get; set; }
        public Nullable<bool> Administrador { get; set; }
        public Nullable<bool> Exclusao { get; set; }
    }
}
